# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20160517_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='study',
            name='start_date',
            field=models.DateField(),
        ),
    ]
