# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_auto_20160530_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='url',
            field=models.URLField(help_text=b'Personal webpage.'),
        ),
    ]
