# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_auto_20160530_0531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='home_address',
            new_name='about',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='url',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
