# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0019_auto_20160530_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
